require('config.lsp.nlua')
require('config.lsp.pyright')
require('config.lsp.efm')
require('config.lsp.yaml')
require('config.lsp.sql')
require('config.lsp.clangd')
require('config.lsp.bash')
require('config.lsp.vimscript')
